### ISSUE TITLE
Very small or non-blocksize-multiple input size may not be decrypting properly

### ISSUE THREAD

**Issue by Intensity** [jedisct1/rust-rocca#1]
I can have some self-contained test cases on this in the coming days to showcase this, although speaking at a high level, I noticed that with this (Rocca) code (but not the similarly designed Morus one), small-sized (< 16 byte) inputs and/or inputs not a multiple of the blocksize, the decryption of an encrypted plaintext didn't return the original. For larger inputs or full integer multiple sizes I believe it was all working correctly. I thought this would be easy to reproduce with some test inputs at those sizes, but if not, please let me know. Note that the very similarly styled implementation for Morus didn't have an issue. Because these have similar design, looking at differences between them may help uncover what's going on. I'm using the encrypt/decrypt in-place mode.

**Comment by jedisct1** [comment]
Thanks!

A copy was indeed missing in the decrypt-in-place function.

It should be fixed now. Thanks!

This copy is just a hack to work around the borrow check, so the Zig version doesn't have the bug.

**Comment by Intensity** [comment]
Thanks! Much appreciated.

I can open up another ticket on a tangential question I have. Although provisionally I'm curious if you have impressions about why the Zig version is relatively much quicker (is it parallelism in Zig? Rust overhead? safety checks that could be disabled?). Also I'm interested to know if there's an opportunity for Rocca to benefit from VAES / multi-buffer optimisations, as per https://github.com/intel/intel-ipsec-mb

**Comment by jedisct1** [comment]
Zig's compiler generally does a much better job than Rust.

Here, the Rust compiler seems to be unable to inline `AESENC` calls, even when directly using the assembly version.

With a single buffer, 256-bit and 512-bit VAES may not be worth it, since the additions would require extra shuffle operations. Something that would be worth benchmarking, but I don't have such hardware.

For multiple buffers, a performance gain is more likely.
